import typing
from typing import overload

class DensePauliArray:
    @overload
    def __init__(self, num_operators: typing.SupportsInt, num_qubits: typing.SupportsInt) -> None: ...
    @overload
    def __init__(self, z_data: typing.SupportsInt, x_data: typing.SupportsInt, num_operators: typing.SupportsInt, num_qubits: typing.SupportsInt) -> None: ...
    def commutes_batch(self, other: DensePauliArray) -> list[bool]: ...
    def compose_batch(self, other: DensePauliArray) -> DensePauliArray: ...
    @staticmethod
    def random(num_operators: typing.SupportsInt, num_qubits: typing.SupportsInt) -> DensePauliArray: ...
    def tensor(self, other: DensePauliArray) -> DensePauliArray: ...
    def to_string(self) -> str: ...
