import collections.abc
import numpy
import numpy.typing
import typing
from typing import overload

class PauliArray:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: collections.abc.Sequence[typing.SupportsInt]) -> None: ...
    @overload
    def __init__(self, arg0: collections.abc.Sequence[typing.SupportsInt], arg1: typing.SupportsInt) -> None: ...
    @overload
    def __init__(self, arg0: collections.abc.Sequence[typing.SupportsInt], arg1: collections.abc.Sequence[typing.SupportsInt], arg2: complex) -> None: ...
    def commutes(self, arg0: PauliArray) -> list[bool]: ...
    def commutes_numpy(self, arg0: PauliArray) -> numpy.typing.NDArray[numpy.uint8]: ...
    def compose(self, arg0: PauliArray) -> PauliArray: ...
    def concatenate(self, arg0: PauliArray) -> PauliArray: ...
    def get_paulis(self) -> list[int]: ...
    def get_x_string(self) -> list[int]: ...
    def get_z_string(self) -> list[int]: ...
    @staticmethod
    def random(arg0: typing.SupportsInt) -> PauliArray: ...
    def size(self) -> int: ...
    def tensor(self, arg0: PauliArray) -> PauliArray: ...
    def zx_to_paulis(self, arg0: collections.abc.Sequence[typing.SupportsInt], arg1: collections.abc.Sequence[typing.SupportsInt]) -> list[int]: ...
