import numpy

def bitwise_and(arg0: numpy.ndarray, arg1: numpy.ndarray) -> numpy.ndarray: ...
def bitwise_count(arg0: numpy.ndarray) -> int: ...
def bitwise_dot(arg0: numpy.ndarray, arg1: numpy.ndarray) -> int: ...
def bitwise_not(arg0: numpy.ndarray) -> numpy.ndarray: ...
def bitwise_xor(arg0: numpy.ndarray, arg1: numpy.ndarray) -> numpy.ndarray: ...
