import collections.abc
import numpy
import numpy.typing
import typing

def bitwise_commute_with(arg0: numpy.ndarray, arg1: numpy.ndarray, arg2: numpy.ndarray, arg3: numpy.ndarray) -> numpy.typing.NDArray[numpy.bool]: ...
def compose(arg0: numpy.ndarray, arg1: numpy.ndarray, arg2: numpy.ndarray, arg3: numpy.ndarray) -> tuple: ...
def random_zx_strings(arg0: collections.abc.Sequence[typing.SupportsInt], arg1: typing.SupportsInt) -> tuple: ...
def tensor(arg0: numpy.ndarray, arg1: numpy.ndarray, arg2: numpy.ndarray, arg3: numpy.ndarray) -> tuple: ...
def unique(zx_voids: numpy.ndarray, return_index: bool = ..., return_inverse: bool = ..., return_counts: bool = ...) -> object: ...
