import collections.abc
import typing

def and_dpoint(arg0: collections.abc.Sequence[tuple[typing.SupportsInt, typing.SupportsInt]], arg1: collections.abc.Sequence[tuple[typing.SupportsInt, typing.SupportsInt]]) -> list[tuple[int, int]]: ...
def make_dpoint(arg0: collections.abc.Sequence[typing.SupportsInt]) -> list[tuple[int, int]]: ...
def not_dpoint(arg0: collections.abc.Sequence[tuple[typing.SupportsInt, typing.SupportsInt]], arg1: typing.SupportsInt) -> list[tuple[int, int]]: ...
def or_dpoint(arg0: collections.abc.Sequence[tuple[typing.SupportsInt, typing.SupportsInt]], arg1: collections.abc.Sequence[tuple[typing.SupportsInt, typing.SupportsInt]]) -> list[tuple[int, int]]: ...
def overlap_dpoint(arg0: collections.abc.Sequence[tuple[typing.SupportsInt, typing.SupportsInt]], arg1: collections.abc.Sequence[tuple[typing.SupportsInt, typing.SupportsInt]]) -> None: ...
def show_dpoints(arg0: collections.abc.Sequence[tuple[typing.SupportsInt, typing.SupportsInt]]) -> None: ...
def xor_dpoint(arg0: collections.abc.Sequence[tuple[typing.SupportsInt, typing.SupportsInt]], arg1: collections.abc.Sequence[tuple[typing.SupportsInt, typing.SupportsInt]]) -> list[tuple[int, int]]: ...
