import numpy

def bitwise_and(voids_1: numpy.ndarray, voids_2: numpy.ndarray) -> numpy.ndarray: ...
def bitwise_count(arg0: numpy.ndarray) -> numpy.ndarray: ...
def bitwise_dot(arg0: numpy.ndarray, arg1: numpy.ndarray) -> numpy.ndarray: ...
def bitwise_not(arg0: numpy.ndarray) -> numpy.ndarray: ...
def bitwise_or(arg0: numpy.ndarray, arg1: numpy.ndarray) -> numpy.ndarray: ...
def bitwise_xor(arg0: numpy.ndarray, arg1: numpy.ndarray) -> numpy.ndarray: ...
